#!/usr/bin/bash

term=$(perl -lpe 's/\0/ /g' \
/proc/$(xdotool getwindowpid $(xdotool getactivewindow))/cmdline)

## Enable extended globbing patterns
shopt -s extglob
case $term in
## If this terminal is a python or perl program,
## then the emulator's name is likely the second 
## part of it
*/python*|*/perl*    )
  term=$(basename "$(readlink -f $(echo "$term" | cut -d ' ' -f 2))")
;;
## The special case of gnome-terminal
*gnome-terminal-server* )
  term="gnome-terminal"
;;
## For other cases, just take the 1st
## field of $term
* )
  term=${term/% */}
;;
esac
echo "$term"
